version: '3.5'

networks:
  dev:
    name: dev
    
services:
  api:
    build: ChatServer/
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - db
      - redis
        
  web:
    build: FrontEnd/    
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api

  db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Andrew123456
    ports:
      - "1433:1433"
  
  redis:
    image: redis
    ports:
      - "6379:6379"