version: '3.5'

networks:
  dev:
    name: dev
    
services:
  api:
    build: .
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - db
      - redis
        
  web:
    build: ChatClient/    
    image: registry.heroku.com/pub-chat-app/web
    restart: always
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - api

  db:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Andrew123456
      - MSSQL_TCP_PORT=1433
    ports:
      - "1400:1433"
  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"